title: Adviso Technologies
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7160853717941791
  brandStrength: 0.5
  rhythmicContrast: 0.7531194256152958
  brandColors:
    - '#b9ca0f'
    - '#ffffff'
    - '#ffac16'
    - '#ffff00'
    - '#ff8000'
  lightness: 0.0917939783539623
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Adviso
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2616487
layout_spectrum: 0
