name: Adviso
favicon: null
layout_spectrum: 0.3242458791937679
typography_spectrum: 0.7359971103724092
title: Adviso Technologies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9ca0f'
    - '#ffffff'
    - '#ffac16'
    - '#ffff00'
    - '#ff8000'
  brandStrength: 0.5
  lightness: 0.0917939783539623
  saturation: 0.7160853717941791
  rhythmicContrast: 0.7531194256152958
purpose: []
